data:extend {
    --- runtime
    {
        type = "double-setting",
        name = "dw-min-richness-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0.1,
        default_value = 0.25,
        maximum_value = 0.9,
        order = "a-a",
    },
    {
        type = "double-setting",
        name = "dw-max-richness-multiplier",
        setting_type = "runtime-global",
        minimum_value = 1.1,
        default_value = 2,
        maximum_value = 4,
        order = "a-b",
    },
    {
        type = "double-setting",
        name = "dw-min-frequency-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0.1,
        default_value = 0.25,
        maximum_value = 0.9,
        order = "a-c",
    },
    {
        type = "double-setting",
        name = "dw-max-frequency-multiplier",
        setting_type = "runtime-global",
        minimum_value = 1.1,
        default_value = 2,
        maximum_value = 4,
        order = "a-d",
    },
    {
        type = "double-setting",
        name = "dw-min-size-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0.1,
        default_value = 0.25,
        maximum_value = 0.9,
        order = "a-e",
    },
    {
        type = "double-setting",
        name = "dw-max-size-multiplier",
        setting_type = "runtime-global",
        minimum_value = 1.1,
        default_value = 2,
        maximum_value = 4,
        order = "a-f",
    },
}