data:extend {
    -- Startup
    {
        type = "bool-setting",
        name = "dw-adjust-stack-size",
        setting_type = "startup",
        default_value = true,
        order = "a-a",
    },
    {
        type = "bool-setting",
        name = "dw-adjust-spoilage",
        setting_type = "startup",
        default_value = true,
        order = "a-b",
    },
    {
        type = "string-setting",
        name = "dw-default-tile-background",
        setting_type = "startup",
        default_value = "empty-space",
        order = "b-a",
    },
    {
        type = "string-setting",
        name = "dw-default-tile-platform",
        setting_type = "startup",
        default_value = "concrete",
        order = "b-b",
    },
    {
        type = "string-setting",
        name = "dw-default-tile-dimensions",
        setting_type = "startup",
        default_value = "tutorial-grid",
        order = "b-c",
    },
    {
        type = "string-setting",
        name = "dw-logistic-chest-input",
        setting_type = "startup",
        default_value = "requester-chest",
        allowed_values = {"steel-chest", "storage-chest", "requester-chest", "buffer-chest"},
        order = "c-a",
    },
    {
        type = "string-setting",
        name = "dw-logistic-chest-output",
        setting_type = "startup",
        default_value = "active-provider-chest",
        allowed_values = {"steel-chest", "storage-chest", "active-provider-chest", "passive-provider-chest", "buffer-chest"},
        order = "c-b",
    },
    {
        type = "bool-setting",
        name = "dw-another-mod-loader",
        setting_type = "startup",
        default_value = false,
        order = "d-a",
    },
    {
        type = "string-setting",
        name = "dw-another-mod-loader-select",
        setting_type = "startup",
        default_value = "aai-loaders",
        allowed_values = {"aai-loaders", "Krastorio2"},
        order = "d-b",
    },

    --- runtime
    {
        type = "double-setting",
        name = "dw-min-richness-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0.1,
        default_value = 0.25,
        maximum_value = 0.9,
        order = "a-a",
    },
    {
        type = "double-setting",
        name = "dw-max-richness-multiplier",
        setting_type = "runtime-global",
        minimum_value = 1.1,
        default_value = 2,
        maximum_value = 4,
        order = "b-a",
    },
    {
        type = "double-setting",
        name = "dw-min-frequency-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0.1,
        default_value = 0.25,
        maximum_value = 0.9,
        order = "a-b",
    },
    {
        type = "double-setting",
        name = "dw-max-frequency-multiplier",
        setting_type = "runtime-global",
        minimum_value = 1.1,
        default_value = 2,
        maximum_value = 4,
        order = "b-b",
    },
    {
        type = "double-setting",
        name = "dw-min-size-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0.1,
        default_value = 0.25,
        maximum_value = 0.9,
        order = "a-c",
    },
    {
        type = "double-setting",
        name = "dw-max-size-multiplier",
        setting_type = "runtime-global",
        minimum_value = 1.1,
        default_value = 2,
        maximum_value = 4,
        order = "b-c",
    },
    {
        type = "double-setting",
        name = "dw-min-warp-voter",
        setting_type = "runtime-global",
        minimum_value = 0.1,
        default_value = 0.5,
        maximum_value = 1,
        order = "c-a",
    },
    {
        type = "int-setting",
        name = "dw-manual-warp-max-time",
        setting_type = "runtime-global",
        minimum_value = 10,
        default_value = 15,
        maximum_value = 60,
        order = "c-b",
    },
    {
        type = "double-setting",
        name = "dw-manual-warp-zone-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0.5,
        default_value = 0.5,
        maximum_value = 2,
        order = "c-c",
    },

}