data:extend {
    -- Startup
    {
        type = "bool-setting",
        name = "dw-adjust-stack-size",
        setting_type = "startup",
        default_value = true,
        order = "a-a",
    },
    {
        type = "bool-setting",
        name = "dw-adjust-spoilage",
        setting_type = "startup",
        default_value = true,
        order = "a-b",
    },
    {
        type = "bool-setting",
        name = "dw-adjust-space-cost",
        setting_type = "startup",
        default_value = true,
        order = "a-c",
    },
    {
        type = "string-setting",
        name = "dw-default-tile-platform",
        setting_type = "startup",
        default_value = "concrete",
        order = "b-b",
    },
    {
        type = "string-setting",
        name = "dw-default-tile-dimensions",
        setting_type = "startup",
        default_value = "tutorial-grid",
        order = "b-c",
    },
    {
        type = "string-setting",
        name = "dw-logistic-chest-input",
        setting_type = "startup",
        default_value = "requester-chest",
        allowed_values = {"steel-chest", "storage-chest", "requester-chest", "buffer-chest"},
        order = "c-a",
    },
    {
        type = "string-setting",
        name = "dw-logistic-chest-output",
        setting_type = "startup",
        default_value = "active-provider-chest",
        allowed_values = {"steel-chest", "storage-chest", "active-provider-chest", "passive-provider-chest", "buffer-chest"},
        order = "c-b",
    },
    {
        type = "bool-setting",
        name = "dw-another-mod-loader",
        setting_type = "startup",
        default_value = false,
        order = "d-a",
    },
    {
        type = "string-setting",
        name = "dw-another-mod-loader-select",
        setting_type = "startup",
        default_value = "aai-loaders",
        allowed_values = {"aai-loaders", "Krastorio2"},
        order = "d-b",
    },

    --- runtime
    {
        type = "double-setting",
        name = "dw-min-warp-voter",
        setting_type = "runtime-global",
        minimum_value = 0.1,
        default_value = 0.51,
        maximum_value = 1,
        order = "a-a",
    },
    {
        type = "int-setting",
        name = "dw-manual-warp-max-time",
        setting_type = "runtime-global",
        minimum_value = 10,
        default_value = 15,
        maximum_value = 60,
        order = "a-b",
    },
    {
        type = "double-setting",
        name = "dw-manual-warp-zone-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0.5,
        default_value = 0.5,
        maximum_value = 2,
        order = "a-c",
    },
    {
        type = "double-setting",
        name = "dw-helper-pollution-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0.1,
        default_value = 1,
        maximum_value = 3,
        order = "b-a",
    },
    {
        type = "bool-setting",
        name = "dw-helper-starter-item",
        setting_type = "runtime-global",
        default_value = false,
        order = "b-b",
    },
    {
        type = "int-setting",
        name = "dw-helper-enemy-force-attack",
        setting_type = "runtime-global",
        minimum_value = 1,
        default_value = 5,
        maximum_value = 25,
        order = "b-c",
    },
    {
        type = "bool-setting",
        name = "dw-harvester-only-one",
        setting_type = "runtime-global",
        default_value = false,
        order = "c-a",
    },



    -- user settings
    {
        type = "string-setting",
        name = "dw-gui-thousand-delimiter",
        setting_type = "runtime-per-user",
        default_value = " ",
        allowed_values = {" ", ",", "."},
        order = "a-a",
    },
    {
        type = "bool-setting",
        name = "dw-gui-highlight-qty-change",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "a-b",
    },
    {
        type = "string-setting",
        name = "dw-gui-default-color",
        setting_type = "runtime-per-user",
        default_value = "#CCCCCC",
        order = "a-c",
    },
    {
        type = "string-setting",
        name = "dw-gui-increase-qty-color",
        setting_type = "runtime-per-user",
        default_value = "#8FDD8F",
        order = "a-d",
    },
    {
        type = "string-setting",
        name = "dw-gui-decrease-qty-color",
        setting_type = "runtime-per-user",
        default_value = "#F0A97A",
        order = "a-e",
    },
    {
        type = "bool-setting",
        name = "dw-gui-info-planet",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "b-a",
    },
    {
        type = "bool-setting",
        name = "dw-gui-info-dimension",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "b-b",
    },
    {
        type = "bool-setting",
        name = "dw-gui-info-planet-clock",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "b-c",
    },
    {
        type = "bool-setting",
        name = "dw-gui-info-evolution",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "b-d",
    },
    {
        type = "bool-setting",
        name = "dw-gui-info-warp-timer",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "b-e",
    },
    {
        type = "bool-setting",
        name = "dw-gui-info-manual-warp-timer",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "b-f",
    },
    {
        type = "bool-setting",
        name = "dw-gui-planet-selector",
        setting_type = "runtime-per-user",
        default_value = true,
        order = "c",
    },
}